# This scripts calls all R-scripts to reproduce analyses SIMPLE paper

# setwd("")
rm(list = ls())
graphics.off()

# SICOPOLIS input and output data generated by
# Applegate et al. 2012
# Applegate et al. 2015
# Applegate and Keller 2015
# is stored in "data/SICOPOLOS_???.txt"
# ??? refers to applied temperature reconstruction/scenario

## source("read.SICOPOLIS.R")

# Plot temperature scenarios
source("plot_temperature_scenarios.R")

# Create figures with equilibrium volumes as a function of Tgrl
# according to SICOPOLIS (Applegate et al. 2014)
source("relate_T_Veq.R")       # creates figure for single 'best' member for main article
                               # creates figure for 27 'best' members for supplement
source("relate_T_errorVeq.R")  # creates error-plots for 27 'best' members for supplement

# Plot relation between predictors (distance to (virtual) equilibrium or temperature) and 
# measures of change (Vdot and change rate)
source("relate_change.R")

# Train semi-empirical models on complete set of 20 geo-engineering scenarios + SICOPOLIS
# simulated response and train on the basis of subsets for cross-validation

source("train_sems.R")       # RUNNING THIS SCRIPT MAY TAKE A WHILE

# Create validation sets
source("constructValidationData.R")

# Plot emulated response to Geo-engineering scenarios
source("plot_emulated_response.R")
source("plot_error_emulated_response.R")

# Estimate and plot RMSE of estimated parameters (trained on different subsets of
# scenarios) for three models
source("estimate_RSME.R")

# Plot run time (CPU) SIMPLE next to other more complex models
source("constructCPUplot.R")


# Plot hysteresis behaviour
source("plot_hysteresis.R")


